 
version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      BUNDLER_VERSION: 2.0.1
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout

      - run: 
        name: setup bundler
        command:
            sudo gem install bundler

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan