# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment:
    steps:
      - checkout
      - run:
      - run:
            name: Setup - Running bundle install
            command: bundle check || bundle install --path vendor/bundle

      - run:
            name: Build and run tests
            command: bundle exec fastlane test
            environment:
             