# .circleci/config.yml
#version: 2
#jobs:
#  build:
#    macos:
#      xcode: "10.1.0"
#    shell: /bin/bash --login -eo pipefail
#    working_directory: /Users/distiller/project
    
    
#    environment:
#    steps:
#      - checkout
#      - run:
#            name: Update Carthage
#            command: carthage update --no-use-binaries --platform iOS
#      - run:
#            name: Build app Carthage
#            command: carthage bootstrap --platform ios --no-use-binaries
#      - run:
#            name: Setup - Running bundle install
#            command: bundle check || bundle install --path vendor/bundle
#      - run:
#            name: Build and run tests
#            command: bundle exec fastlane test
#            environment:

version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
#      - restore_cache:
#          key: 1-gems-{{ checksum "Gemfile.lock" }}
#      - run: carthage bootstrap
      - run: bundle install
      - run: bundle update
      - run: bundle version
      - run: bundle check || bundle install --path vendor/bundle
#      - save_cache:
#          key: 1-gems-{{ checksum "Gemfile.lock" }}
#          paths:
#            - vendor/bundle
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
             